// Code generated by fastssz. DO NOT EDIT.
// Hash: 6b1f21194a6dd7d468868013c6f418717ff9b1a46497537e2f7ab040fdd6217d
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Config object
func (c *Config) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the Config object to a target array
func (c *Config) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, c.GenesisTime)

	return
}

// UnmarshalSSZ ssz unmarshals the Config object
func (c *Config) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return ssz.ErrSize
	}

	// Field (0) 'GenesisTime'
	c.GenesisTime = ssz.UnmarshallUint64(buf[0:8])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Config object
func (c *Config) SizeSSZ() (size int) {
	size = 8
	return
}

// HashTreeRoot ssz hashes the Config object
func (c *Config) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the Config object with a hasher
func (c *Config) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'GenesisTime'
	hh.PutUint64(c.GenesisTime)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Config object
func (c *Config) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}
