// Code generated by fastssz. DO NOT EDIT.
// Hash: 6b1f21194a6dd7d468868013c6f418717ff9b1a46497537e2f7ab040fdd6217d
// Version: 0.1.3
package types

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Validator object
func (v *Validator) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the Validator object to a target array
func (v *Validator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Pubkey'
	dst = append(dst, v.Pubkey[:]...)

	// Field (1) 'Index'
	dst = ssz.MarshalUint64(dst, v.Index)

	return
}

// UnmarshalSSZ ssz unmarshals the Validator object
func (v *Validator) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 60 {
		return ssz.ErrSize
	}

	// Field (0) 'Pubkey'
	copy(v.Pubkey[:], buf[0:52])

	// Field (1) 'Index'
	v.Index = ssz.UnmarshallUint64(buf[52:60])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Validator object
func (v *Validator) SizeSSZ() (size int) {
	size = 60
	return
}

// HashTreeRoot ssz hashes the Validator object
func (v *Validator) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the Validator object with a hasher
func (v *Validator) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Pubkey'
	hh.PutBytes(v.Pubkey[:])

	// Field (1) 'Index'
	hh.PutUint64(v.Index)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Validator object
func (v *Validator) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}

// MarshalSSZ ssz marshals the State object
func (s *State) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(s)
}

// MarshalSSZTo ssz marshals the State object to a target array
func (s *State) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(228)

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if dst, err = s.Config.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if dst, err = s.LatestBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if dst, err = s.LatestJustified.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if dst, err = s.LatestFinalized.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (5) 'HistoricalBlockHashes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.HistoricalBlockHashes) * 32

	// Offset (6) 'JustifiedSlots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustifiedSlots)

	// Offset (7) 'Validators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.Validators) * 60

	// Offset (8) 'JustificationsRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(s.JustificationsRoots) * 32

	// Offset (9) 'JustificationsValidators'
	dst = ssz.WriteOffset(dst, offset)

	// Field (5) 'HistoricalBlockHashes'
	if size := len(s.HistoricalBlockHashes); size > 262144 {
		err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
		return
	}
	for ii := 0; ii < len(s.HistoricalBlockHashes); ii++ {
		dst = append(dst, s.HistoricalBlockHashes[ii][:]...)
	}

	// Field (6) 'JustifiedSlots'
	if size := len(s.JustifiedSlots); size > 262144 {
		err = ssz.ErrBytesLengthFn("State.JustifiedSlots", size, 262144)
		return
	}
	dst = append(dst, s.JustifiedSlots...)

	// Field (7) 'Validators'
	if size := len(s.Validators); size > 4096 {
		err = ssz.ErrListTooBigFn("State.Validators", size, 4096)
		return
	}
	for ii := 0; ii < len(s.Validators); ii++ {
		if dst, err = s.Validators[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (8) 'JustificationsRoots'
	if size := len(s.JustificationsRoots); size > 262144 {
		err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
		return
	}
	for ii := 0; ii < len(s.JustificationsRoots); ii++ {
		dst = append(dst, s.JustificationsRoots[ii][:]...)
	}

	// Field (9) 'JustificationsValidators'
	if size := len(s.JustificationsValidators); size > 1073741824 {
		err = ssz.ErrBytesLengthFn("State.JustificationsValidators", size, 1073741824)
		return
	}
	dst = append(dst, s.JustificationsValidators...)

	return
}

// UnmarshalSSZ ssz unmarshals the State object
func (s *State) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 228 {
		return ssz.ErrSize
	}

	tail := buf
	var o5, o6, o7, o8, o9 uint64

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if err = s.Config.UnmarshalSSZ(buf[0:8]); err != nil {
		return err
	}

	// Field (1) 'Slot'
	s.Slot = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.UnmarshalSSZ(buf[16:128]); err != nil {
		return err
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.UnmarshalSSZ(buf[128:168]); err != nil {
		return err
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.UnmarshalSSZ(buf[168:208]); err != nil {
		return err
	}

	// Offset (5) 'HistoricalBlockHashes'
	if o5 = ssz.ReadOffset(buf[208:212]); o5 > size {
		return ssz.ErrOffset
	}

	if o5 != 228 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (6) 'JustifiedSlots'
	if o6 = ssz.ReadOffset(buf[212:216]); o6 > size || o5 > o6 {
		return ssz.ErrOffset
	}

	// Offset (7) 'Validators'
	if o7 = ssz.ReadOffset(buf[216:220]); o7 > size || o6 > o7 {
		return ssz.ErrOffset
	}

	// Offset (8) 'JustificationsRoots'
	if o8 = ssz.ReadOffset(buf[220:224]); o8 > size || o7 > o8 {
		return ssz.ErrOffset
	}

	// Offset (9) 'JustificationsValidators'
	if o9 = ssz.ReadOffset(buf[224:228]); o9 > size || o8 > o9 {
		return ssz.ErrOffset
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		buf = tail[o5:o6]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.HistoricalBlockHashes = make([][32]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(s.HistoricalBlockHashes[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (6) 'JustifiedSlots'
	{
		buf = tail[o6:o7]
		if err = ssz.ValidateBitlist(buf, 262144); err != nil {
			return err
		}
		if cap(s.JustifiedSlots) == 0 {
			s.JustifiedSlots = make([]byte, 0, len(buf))
		}
		s.JustifiedSlots = append(s.JustifiedSlots, buf...)
	}

	// Field (7) 'Validators'
	{
		buf = tail[o7:o8]
		num, err := ssz.DivideInt2(len(buf), 60, 4096)
		if err != nil {
			return err
		}
		s.Validators = make([]*Validator, num)
		for ii := 0; ii < num; ii++ {
			if s.Validators[ii] == nil {
				s.Validators[ii] = new(Validator)
			}
			if err = s.Validators[ii].UnmarshalSSZ(buf[ii*60 : (ii+1)*60]); err != nil {
				return err
			}
		}
	}

	// Field (8) 'JustificationsRoots'
	{
		buf = tail[o8:o9]
		num, err := ssz.DivideInt2(len(buf), 32, 262144)
		if err != nil {
			return err
		}
		s.JustificationsRoots = make([][32]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(s.JustificationsRoots[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (9) 'JustificationsValidators'
	{
		buf = tail[o9:]
		if err = ssz.ValidateBitlist(buf, 1073741824); err != nil {
			return err
		}
		if cap(s.JustificationsValidators) == 0 {
			s.JustificationsValidators = make([]byte, 0, len(buf))
		}
		s.JustificationsValidators = append(s.JustificationsValidators, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the State object
func (s *State) SizeSSZ() (size int) {
	size = 228

	// Field (5) 'HistoricalBlockHashes'
	size += len(s.HistoricalBlockHashes) * 32

	// Field (6) 'JustifiedSlots'
	size += len(s.JustifiedSlots)

	// Field (7) 'Validators'
	size += len(s.Validators) * 60

	// Field (8) 'JustificationsRoots'
	size += len(s.JustificationsRoots) * 32

	// Field (9) 'JustificationsValidators'
	size += len(s.JustificationsValidators)

	return
}

// HashTreeRoot ssz hashes the State object
func (s *State) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(s)
}

// HashTreeRootWith ssz hashes the State object with a hasher
func (s *State) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Config'
	if s.Config == nil {
		s.Config = new(Config)
	}
	if err = s.Config.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Slot'
	hh.PutUint64(s.Slot)

	// Field (2) 'LatestBlockHeader'
	if s.LatestBlockHeader == nil {
		s.LatestBlockHeader = new(BlockHeader)
	}
	if err = s.LatestBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (3) 'LatestJustified'
	if s.LatestJustified == nil {
		s.LatestJustified = new(Checkpoint)
	}
	if err = s.LatestJustified.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'LatestFinalized'
	if s.LatestFinalized == nil {
		s.LatestFinalized = new(Checkpoint)
	}
	if err = s.LatestFinalized.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'HistoricalBlockHashes'
	{
		if size := len(s.HistoricalBlockHashes); size > 262144 {
			err = ssz.ErrListTooBigFn("State.HistoricalBlockHashes", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.HistoricalBlockHashes {
			hh.Append(i[:])
		}
		numItems := uint64(len(s.HistoricalBlockHashes))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (6) 'JustifiedSlots'
	if len(s.JustifiedSlots) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustifiedSlots, 262144)

	// Field (7) 'Validators'
	{
		subIndx := hh.Index()
		num := uint64(len(s.Validators))
		if num > 4096 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range s.Validators {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4096)
	}

	// Field (8) 'JustificationsRoots'
	{
		if size := len(s.JustificationsRoots); size > 262144 {
			err = ssz.ErrListTooBigFn("State.JustificationsRoots", size, 262144)
			return
		}
		subIndx := hh.Index()
		for _, i := range s.JustificationsRoots {
			hh.Append(i[:])
		}
		numItems := uint64(len(s.JustificationsRoots))
		hh.MerkleizeWithMixin(subIndx, numItems, 262144)
	}

	// Field (9) 'JustificationsValidators'
	if len(s.JustificationsValidators) == 0 {
		err = ssz.ErrEmptyBitlist
		return
	}
	hh.PutBitlist(s.JustificationsValidators, 1073741824)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the State object
func (s *State) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(s)
}
